---
spring:
  config.activate.on-profile: cloudpeers
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}othereureka.credentials.uri:http://${PREFIX:}othereureka.${application.domain:cfapps.io}}/eureka/

---
spring:
  config.activate.on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
